## Workflow 이름
name: Deploy to ECR

### Event 새로운 버전 릴리즈시 tag시
on:
  push:
    tags:
      - 'v*.*.*'

### build이라는 Job 명시 Runner는 기본값 
### 여기서부터 이루어지는 모든작업은 가상머신에서 실행
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    ## Step 하나하나 실행 
    steps:
      
    ## 브랜치 스위칭  
    - name: Check out code
      uses: actions/checkout@v3

    ## 릴리즈 버전 저장
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    ## AWS 자격증명 확인
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secret.AWS_ECR_ASSUME }}
        aws-region: ap-northeast-2
    
    ## AWS ECR의 로그인
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    ## build and push 진행
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: test
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION
