## Workflow 이름
name: Deploy to ECR

### Event! 지정 main 브랜치 push
on:
  push:
    branches: [ main ]

### build이라는 Job 명시 Runner는 기본값 
### 여기서부터 이루어지는 모든작업은 가상머신에서 실행
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    ## Step 하나하나 실행 
    steps:
      
    ## 브랜치 스위칭  
    - name: Check out code
      uses: actions/checkout@v3
    
    ## AWS 자격증명 확인
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    ## AWS ECR의 로그인
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    ## build and push 진행
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: test
        IMAGE_TAG: 0.0.2
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
