name: Docker Hub push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
			### branch 스위칭
      - name: Checkout
        uses: actions/checkout@v3
			
			### Qemu를 runner안에서 따로 띄운다.
      -name: Set up QEMU
        uses: docker/setup-qemu-action@v3

			### qemu안에서 Docker Buildx로 빌드를 진행
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

			### 도커허브 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

			### Dockerfile의 위치는 Repo에 '/' 
      - name: Build and push
        uses: docker/build-push-action@v3
				env:
          IMAGE_NAME: nginx-test
					IMAGE_TAG: 0.0.1
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG